### ISSUE TITLE
Tracking steps per demo video

### ISSUE THREAD

**Issue by gallaeli** [gallaeli/project-practice#2]
### Will the Phillies win the World Series?

- [ ] create a branch
- [ ] create some commits
- [ ] open a pull request
- [ ] collaborate & additional commits
- [ ] merge
